### ISSUE TITLE
KISSY 模块自由配置工具-自定义模块链接404

### ISSUE THREAD

**Issue by huixisheng** [kissyteam/kissy#715]
[KISSY 模块自由配置工具](http://docs.kissyui.com/1.4/docs/html/guideline/config.html) 生成的链接404
例如 [http://g.alicdn.com/kissy/k/1.4.8/??seed-min.js,dom-min.js,event-min.js,io-min.js,anim-min.js,base-min.js,node-min.js,json-min.js,ua-min.js,cookie-min.js,core-min.js](http://g.alicdn.com/kissy/k/1.4.8/??seed-min.js,dom-min.js,event-min.js,io-min.js,anim-min.js,base-min.js,node-min.js,json-min.js,ua-min.js,cookie-min.js,core-min.js)无法访问

**Comment by weekeight** [comment]
'模块自由配置工具' 指的是什么？拼出来的路径有问题

**Comment by huixisheng** [comment]
[KISSY 模块自由配置工具](http://docs.kissyui.com/1.4/docs/html/guideline/config.html) 生成的链接404

**Comment by weekeight** [comment]
1.4版本的用动态combo的吧，别用着工具生成了（这工具估计也是出问题了）
