### ISSUE TITLE
.css关键字的兼容

### ISSUE THREAD

**Issue by flyinhigh** [kissyteam/kissy#716]
如果jsonp请求的链接里带有.css，那么会将其作为css文件去请求，然后不会触发回调。
刚好spm里可能会带，而请求的api把location.search里的参数加进去了，然后就悲剧了。
http://htjhzp.tmall.com/tryshop.htm?spm=a1z0i.1000799.1996938089.22.CSS1wF&id=19028213

**Comment by weekeight** [comment]
根本问题出在path模块，具体看这个[issue](https://github.com/kissyteam/path/issues/1)
